server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
#  mvc:
#    view:
#      prefix: /WEB-INF/views/
#      suffix: .jsp
  mustache:
    suffix: .html
    expose-session-attributes: true  # session처리 및 ui에서 머스테치 사용하기 위한 설정

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/isma?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: user01
    password: user01

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update  # create, update, run 등 설정
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl # entity파일의 변수명이 그대로 컬럼명이 된다는 의미
      use-new-id-generator-mappings: false  # JPA의 기본 넘버링을 따라가지 않는다, true: 따른다.
    show-sql: false  # 톰캣 부팅 시 sql 실행을 콘솔에 보여줌
    properties:
      hibernate.format_sql: true  # 부팅 시 sql 실행을 보기좋게 콘솔에 보여줌

  jackson:
    serialization:
      fail-on-empty-beans: false

# 카카오 로그인 시  사용
kye:
  key: kye1234
